- hosts: DC1_FABRIC
  tasks:
    - name: create local output folders
      import_role:
         name: arista.avd.build_output_folders
      run_once: true

    - name: generate intented variables
      import_role:
         name: arista.avd.eos_l3ls_evpn

    - name: generate device intended config and documention
      import_role:
         name: arista.avd.eos_cli_config_gen