---
- name: Build Switch configuration
  hosts: CVP-1
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
  - name: 'upload configlets to cloudvision {{inventory_hostname}}'
    import_role:
      name: arista.avd.cvp_configlet_upload
    vars:
      configlet_directory: '{{ configlet_dir_var }}'
      configlets_cvp_prefix: '{{ configlets_prefix_var }}'
      file_extension: '{{ configlet_file_extension }}'
